package servidor;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import objetos.PacienteAlta;

/**
 *
 * @author ramssrez
 */
public class ServidorInterfaz extends javax.swing.JFrame implements Runnable {

    private final String HOST = "127.0.0.1";
    private final int PUERTOSERVIDOR = 5000;
    private final int PUERTOCLIENTE = 5050;
    private int contador = 0;
    private final String dr1 = "Dr. Juan Sanchez Sanchez";
    private final String dr2 = "Dra. Irma Fernandez Fernandez";
    private final String dr3 = "Dr. Carlos Leon Leon";
    private final String dr4 = "Dra. Rosa Mercado Mercado";
    private final String dr5 = "Dr. Rodrigo Leyva Leyva";
    private final String dr6 = "Dra. Sofia Lazcano Lazcano";
    private final String dr7 = "Dr. Gerardo Martinez Martinez";
    private final String dr8 = "Dra. Alma Diaz Diaz";
    private final String dr9 = "Dr. Jose Rodriguez Rodrioguez";
    private final String dr10 = "Dra. Selena Sanchez Sanchez";

    String[] doctores = {dr1, dr2, dr3, dr4, dr5, dr6, dr7, dr8, dr9, dr10};

    /**
     * Creates new form CrearArchivos
     */
    public ServidorInterfaz() {
        initComponents();
        this.setTitle("Servidor");
        this.setLocationRelativeTo(null);
        //Sentencia que desactiva el minimizar y maximizar de las ventanas principales
        this.setResizable(false);
        jtfRegistro.setEditable(false);
        Thread thread = new Thread(this);
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtfRegistro = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hospital General: Servidor");

        jtfRegistro.setColumns(20);
        jtfRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfRegistro.setRows(5);
        jtfRegistro.setToolTipText("");
        jtfRegistro.setAutoscrolls(false);
        jScrollPane2.setViewportView(jtfRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServidorInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtfRegistro;
    // End of variables declaration//GEN-END:variables

    //]Uso del método run, el cual es necesario usar por la implementación de runneable
    @Override
    public void run() {
        System.out.println("Esto es desde el hilo servidor");
        PacienteAlta pacienteAlta;

        try {
            String name;
            ServerSocket servidor = new ServerSocket(PUERTOSERVIDOR);
            while(true){
                Socket socket = servidor.accept();
                if (contador == 10) {
                    contador = 0;
                }
                ObjectInputStream inputStream = new ObjectInputStream(socket.getInputStream());
                pacienteAlta = (PacienteAlta) inputStream.readObject();
                name = pacienteAlta.getNombre();
                String message = "\n El paciente " + name + " fue registrado exitosamente";
                jtfRegistro.setText(message);
                pacienteAlta.setDoctorAsignado(doctores[contador]);
                String consultorio = String.valueOf(contador + 2);
                pacienteAlta.setNumeroConsultorio(consultorio);
                String turno = String.valueOf(contador + 1);
                pacienteAlta.setNumeroTurno(turno);
                //System.out.println(pacienteAlta.toString());
                Socket socketRespuesta = new Socket(HOST,PUERTOCLIENTE);
                ObjectOutputStream envioCliente = new ObjectOutputStream(socketRespuesta.getOutputStream());
                envioCliente.writeObject(pacienteAlta);
                socketRespuesta.close();
                socket.close();
                contador++;
            }
            
            
        } catch (IOException ex) {
            System.out.println("Error Selección: " + ex.getMessage());
            ex.printStackTrace(System.out);
        }catch (ClassNotFoundException ex) {
            System.out.println("Error Selección: " + ex.getMessage());
            ex.printStackTrace(System.out);
        }
    }
}
