package interfaces;

import database.PersonalDAO;
import javax.swing.JOptionPane;
import objetos.Personal;

/**
 *
 * @author ramssrez
 */
public class PersonalInterface extends javax.swing.JFrame {

    public PersonalInterface() {
        initComponents();
        this.setTitle("Personal");
        this.setLocationRelativeTo(null);
        //Sentencia que desactiva el minimizar y maximizar de las ventanas principales
        this.setResizable(false);

    }

    //Método que limpia los campos de texto que se utilizaron
    public void limpiarCampos() {
        jtfNumberWorker.setText("");
        jtfName.setText("");
        jtfApellidos.setText("");
        jtfArea.setText("");
        jtfEdad.setText("");
        jtfPuesto.setText("");
        jtfSueldo.setText("");
    }

    //Método que verifica que los campos no se encuentren vacios
    public boolean validacionCamposTexto() {

        if ((jtfApellidos.getText().equals("") && jtfNumberWorker.getText().equals("") && jtfName.getText().equals("")
                && jtfArea.getText().equals("") && jtfEdad.getText().equals("") && jtfPuesto.getText().equals("")
                && jtfSueldo.getText().equals(""))
                || jtfApellidos.getText().equals("") || jtfNumberWorker.getText().equals("") || jtfName.getText().equals("")
                || jtfArea.getText().equals("") || jtfEdad.getText().equals("") || jtfPuesto.getText().equals("")
                || jtfSueldo.getText().equals("")) {
            //Retorno falso en caso de que sea correcto los campos vacios
            return false;
        } else {
            //Retorno verdadero para el caso de que los campos esten llenos
            return true;
        }
    }

    //Método que crea las reservación y la inserta en la base de datos
    public void crearPersonal() {
        //Recuperación de la información desde las cajas de texto
        String nombre = jtfName.getText();
        String numeroTrabajdor = jtfNumberWorker.getText();
        String edad = jtfEdad.getText();
        String apellidos = jtfApellidos.getText();
        String area = jtfArea.getText();
        String puesto = jtfPuesto.getText();
        String sueldo = jtfSueldo.getText();
        //Creación del objeto Personal
        Personal personal = new Personal(nombre, apellidos, area, edad, numeroTrabajdor, puesto, sueldo);
        PersonalDAO pdao = new PersonalDAO();
        //Llamado del metodo para insertar datos a la base de datos
        int entero = pdao.insertar(personal);
        //Musetra de dialogs en caso de que se agreguen correctamente los datos a la base de datos
        if (entero > 0) {
            //Llamado al Dialog que manda un mensaje que se ha realizado correctamente el ingreso de información en la base de datos
            JOptionPane.showMessageDialog(null, "Se han creado un personal");
            //Método que limpia las cajas de texto de la interface
            limpiarCampos();
        } else {
            //Llamado al Dialog que manda un mensaje que se ha realizado correctamente el ingreso de información en la base de datos
            JOptionPane.showMessageDialog(null, "No se ha creado un pesonal");
            //Método que limpia las cajas de texto de la interface
            limpiarCampos();
        }
        //Comienzo del contador de las horas por medio de hilos
        //contadorHoras(dias);
    }

    public void retornarEmpleado() {
        String numeroEmpleado = jtfNumberWorker.getText();
        //Instancia de la clase ProductoDAO
        PersonalDAO personalDAO = new PersonalDAO();
        //Declaración del objeto producto como nul
        Personal p = personalDAO.seleccionar(numeroEmpleado);
        if (p != null) {
            jtfName.setText(p.getNombre());
            jtfApellidos.setText(p.getApellidos());
            jtfNumberWorker.setText(p.getNumeroEmpleado());
            jtfArea.setText(p.getArea());
            jtfEdad.setText(p.getEdad());
            jtfPuesto.setText(p.getPuesto());
            jtfSueldo.setText(p.getSueldo());
        } else {
            JOptionPane.showMessageDialog(null, "Este personal no existe");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNumberWorker = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbtnCrear = new javax.swing.JButton();
        jtfApellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfSueldo = new javax.swing.JTextField();
        jtfArea = new javax.swing.JTextField();
        jtfEdad = new javax.swing.JTextField();
        jtfPuesto = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmtMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("La Estancia");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Número de Empleado");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Alta de personal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");

        jtfNumberWorker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfNumberWorker.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNumberWorker.setText("12345");
        jtfNumberWorker.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Apellidos");

        jtfName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfName.setText("Jorge");
        jtfName.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Puesto");

        jbtnCrear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnCrear.setText(" Crear Personal");
        jbtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearActionPerformed(evt);
            }
        });

        jtfApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfApellidos.setText("Negrete Sanchez");
        jtfApellidos.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Edad");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sueldo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Área");

        jtfSueldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfSueldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfSueldo.setText("12000");
        jtfSueldo.setToolTipText("");

        jtfArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfArea.setText("Recursos Humanos");
        jtfArea.setToolTipText("");

        jtfEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfEdad.setText("39");
        jtfEdad.setToolTipText("");

        jtfPuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfPuesto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPuesto.setText("Coordinador");
        jtfPuesto.setToolTipText("");

        jbtnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnBuscar.setText("Buscar Personal");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jMenu1.setText("Menú Principal");

        jmtMenu.setText("ir");
        jmtMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jmtMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 121, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(171, 171, 171))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNumberWorker)
                            .addComponent(jtfName)
                            .addComponent(jtfApellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfEdad)
                            .addComponent(jtfPuesto)
                            .addComponent(jtfSueldo)
                            .addComponent(jtfArea, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnBuscar)
                    .addComponent(jbtnCrear))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNumberWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnCrear)
                .addGap(18, 18, 18)
                .addComponent(jbtnBuscar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método asignado al boton 
    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
        //Validación de los campos para que no se encuentren vacios
        if (validacionCamposTexto()) {
            JOptionPane.showMessageDialog(null, "Los campos se encuentran Llenos");
            crearPersonal();
        } else {
            //Impresión del dialog en caso de que los campos se encuentrn vacios
            JOptionPane.showMessageDialog(null, "Los campos se encuentran vacios");
        }
    }//GEN-LAST:event_jbtnCrearActionPerformed

    private void jmtMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtMenuActionPerformed
        // TODO add your handling code here:
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmtMenuActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        //Personal p = retornarEmpleado();
        retornarEmpleado();
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JMenuItem jmtMenu;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfArea;
    private javax.swing.JTextField jtfEdad;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfNumberWorker;
    private javax.swing.JTextField jtfPuesto;
    private javax.swing.JTextField jtfSueldo;
    // End of variables declaration//GEN-END:variables
}
